### PR TITLE
[FIX] [11.0] Fix tests broken by last change in muk_converter

### PR DESCRIPTION
**Pull request by katyukha**

### CODE REVIEW

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/25c41991e41acc9d5fad2303dba2ee86e63d29ef

**Comment by katyukha** [comment]
This PR is not related to 25c4199

**Comment by Kerrim-** [comment]
Hi,

I can't accept prs right now because of our ci workflow. Can you confirm that this commits implement your fixes: https://github.com/muk-it/muk_base/commit/e8f3fc56c46271eab34a80441e5f67c84d6af446 https://github.com/muk-it/muk_base/commit/63fd11e118325c6266bd442b41ba4239375ec502

Regards,
Kerrim

**Comment by katyukha** [comment]
Hi, looks good)

**Pull request closed without merging**
